### ISSUE TITLE
Linking static MKL libraries

### ISSUE THREAD

**Issue by piyueh** [NVIDIA/AMGX#101]
At [this line](https://github.com/NVIDIA/AMGX/blob/d0019e5d32e99e7d679b3b773cf16b6f8e7da6f9/CMakeLists.txt#L343) in the `CMakeLists.txt`, MKL is hard-coded to be static libraries regardless of whether we are building static or shared AmgX lib. Is there a specific reason AmgX must be built with static MKL lib?

**Comment by marsaev** [comment]
No, there is no specific reason.
I think it's a good idea to link MKL shared libraries. Ideally i would just plugin something like official FindMKL CMake module, but i don't think there is any. If i remember correcly MKL is kinda sensitive to the flags so from version to version set of flags/libraries might differ, so we locked supported MKL version for now. It might be reasonable to write own module and keep supported versions there instead of picking only one though.

**Comment by piyueh** [comment]
Got it, thanks!

The reason I asked is that I'm packaging AmgX for Arch Linux's AUR: [https://aur.archlinux.org/packages/amgx/](https://aur.archlinux.org/packages/amgx/)

Currently, it does not use MKL. I would like to enable the MKL support for this AUR package. But the official MKL package shipped with Arch Linux's repository only has shared libraries, so I was trying to see if linking shared MKL libraries would cause any issue.
