### ISSUE TITLE
Shock Wave Solvers

### ISSUE THREAD

**Issue by vmasyagin** [NVIDIA/AMGX#113]
Good day to all.

Please tell me where you can read a description of the solvers implemented in the library. In particular, I am interested in which solvers are recommended to be used in the problem with shock waves. For example, in this one (https://www.mso.anu.edu.au/fyris/2dmachstep.html). I am also interested in which solver is more suitable for the next problem (https://cfd-online.com/Wiki/Flow_around_a_circular_cylinder). Thank you in advance.

**Comment by mattmartineau** [comment]
I imagine you have moved past this since posting this issue. 

The solvers available in AmgX can be determined from the documentation https://github.com/NVIDIA/AMGX/tree/main/doc.

I would suggest in cases where you are trying to solve problems for a particular domain you discuss with CFD domain expert colleagues to get some hints first, for example you need to determine symmetry for the choice of Krylov and then the choice of preconditioner depends upon a number of other factors. 

You can take advantage of the runtime-configurability of AmgX for parameter studies to determine which solver converges most efficiently for your problem.
