### ISSUE TITLE
Inserting debug prints

### ISSUE THREAD

**Issue by Tongdongq** [NVIDIA/AMGX#61]
Is there a way to easily insert debug prints in the library?
For example, I want to create a file with the X and B vector for every iteration. base/src/solver.cu:solve() contains the main iteration loop, and calls solve_iteration(b, x, xIsZero).
They are declared as 'Vector<TConfig> &' as parameters, the solver I use (PBICGSTAB) receives 'VVector &' type parameters.
I tried 'printf("%.5e\n", b[i]); in pbicgstab_solver.cu, but it warns 'non-POD class type passed through ellipsis' and it prints zeros for b, where it should be ones. The value of x starts at zeros (initial guess), but is 6.9e-310 (smallest positive value) in subsequent iterations.
'printf("%.5e\n", b.pod()[i]); , but it results in a SIGSEGV
Printing the types of 'x.pod()' and 'x.pod[0]' result in 'N4amgx9PODVectorIdiEE' and 'd' respectively.

**Comment by marsaev** [comment]
You mean in the library code itself or the driver application?
You should be careful with interpreting print results from withing library itself, since data layout might be different from what you expect, but you can try using functions in https://github.com/NVIDIA/AMGX/blob/master/base/include/util.h

**Comment by Tongdongq** [comment]
I meant in the library itself, so I can see what the values are between iterations.
Those functions are very helpful, thank you!
