### ISSUE TITLE
No host implementation of the dense LU solver

### ISSUE THREAD

**Issue by lucasbekker** [NVIDIA/AMGX#62]
I get the following error message:

"Caught amgx exception: No host implementation of the dense LU solver"

How can I fix this?

I use the following configuration: (mode=hDDI)
config_version=2
solver(main)=FGMRES
main:max_iters=300
main:convergence=RELATIVE_MAX
main:tolerance=0.00000001
main:monitor_residual=1
main:preconditioner(amg)=AMG
main:print_solve_stats=1
amg:algorithm=CLASSICAL
amg:cycle=V
amg:max_iters=1
amg:max_levels=10
amg:smoother(amg_smoother)=BLOCK_JACOBI
amg:relaxation_factor=0.75
amg:presweeps=1
amg:postsweeps=2
amg:coarsest_sweeps=4
determinism_flag=1

Exact output:
AMGX version 2.0.0.130-opensource
Built on May 21 2019, 15:47:45
Compiled with CUDA Runtime 10.0, using CUDA driver 10.2
Cannot read file as JSON object, trying as AMGX config
Caught amgx exception: No host implementation of the dense LU solver
 at: /home/lucas/Repositories/AMGX-master/core/include/solvers/dense_lu_solver.h:65

More information:
Ubuntu 18.04 (gcc 7.4)
CUDA 10.0
AMGX source from git master at: 21st of may
Build using MKL 2019.3-062 and MAGMA 2.3.0

**Comment by marsaev** [comment]
The mode you use (mode=hDDI) will try build solver on the host without GPU acceleration, is it intended?

**Comment by lucasbekker** [comment]
Yes

**Comment by marsaev** [comment]
Got it. Not every solver has CPU counterpart, in this case this is dense LU solver which is used by default for the coarsest level of multigrid. 
1) You can try to implement host implementation (see methods in https://github.com/NVIDIA/AMGX/blob/a46b3112bc563592b8d794ba95e57350d282d584/core/include/solvers/dense_lu_solver.h#L46) by using MKL's potrf, for example.
2) You can change default coarse solver by using this configuration parameter:
> amgx:coarse_solver=NOSOLVER

NOSOLVER is basically noop. You can choose other smoother for the coarsest level, of coarse, i.e. same block jacobi.

Also, note that currently you have this configuration parameter:
>amg:coarsest_sweeps=4

is useless with DENSE_LU_SOLVER, since it solves for exact residual and 1 iteration is enough

**Comment by lucasbekker** [comment]
Thank you.

Where can I find a list of available dense solvers?

**Comment by marsaev** [comment]
Any solver can be used as a coarse solver - even another multigrid. We have only one dense solver though - DENSE_LU_SOLVER.

**Comment by lucasbekker** [comment]
Ok, it seems like it might be a good idea to implement a dense lu solver for the host in that case. I will have a look at the possibility of making that happen, would you be open to upstreaming that work if it is of sufficient quality?

**Comment by Tongdongq** [comment]
They are generally open to Pull Requests (see tab), so I'd say yes.

**Comment by marsaev** [comment]
Well, we don't really have CONTRIBUTING rules, but if you keep everything in the same codestyle that would be fine. We don't want to have hard dependence on MKL (maybe optional, ruled by CMake flags), so i would expect c++ implementation.
